# Generated by Django 5.1.4 on 2026-09-10 18:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Internal reference, e.g. BLR-01",
                        max_length=32,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("address", models.CharField(blank=True, max_length=300)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=2)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("timezone", models.CharField(default="Asia/Kolkata", max_length=64)),
                ("working_hours", models.JSONField(blank=True, default=dict)),
                ("contact_name", models.CharField(blank=True, max_length=120)),
                ("contact_phone", models.CharField(blank=True, max_length=32)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="accounts.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                ("employee_code", models.CharField(blank=True, max_length=64)),
                ("full_name", models.CharField(max_length=180)),
                ("role", models.CharField(blank=True, max_length=120)),
                ("department", models.CharField(blank=True, max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="employees/photos/"
                    ),
                ),
                ("face_embedding", models.JSONField(blank=True, default=list)),
                ("enrolment_samples", models.PositiveIntegerField(default=0)),
                ("enrolled_at", models.DateTimeField(blank=True, null=True)),
                ("embedding_model", models.CharField(blank=True, max_length=80)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("consent_given", models.BooleanField(default=False)),
                ("consent_recorded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="accounts.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sites",
                    models.ManyToManyField(
                        blank=True, related_name="employees", to="cameras.site"
                    ),
                ),
            ],
            options={
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                (
                    "location_note",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Above the main entrance'",
                        max_length=200,
                    ),
                ),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("rtsp", "RTSP"),
                            ("http", "HTTP / MJPEG"),
                            ("onvif", "ONVIF"),
                            ("hls", "HLS"),
                            ("file", "Video file"),
                            ("demo", "Simulated (demo)"),
                        ],
                        default="rtsp",
                        max_length=10,
                    ),
                ),
                ("stream_url", models.CharField(blank=True, max_length=500)),
                ("username", models.CharField(blank=True, max_length=120)),
                ("password", models.CharField(blank=True, max_length=200)),
                ("onvif_host", models.CharField(blank=True, max_length=200)),
                ("onvif_port", models.PositiveIntegerField(default=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("degraded", "Degraded"),
                            ("disabled", "Disabled"),
                            ("pending", "Pending setup"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("status_detail", models.CharField(blank=True, max_length=300)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("last_frame_at", models.DateTimeField(blank=True, null=True)),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                ("resolution_width", models.PositiveIntegerField(default=1920)),
                ("resolution_height", models.PositiveIntegerField(default=1080)),
                ("source_fps", models.FloatField(default=25.0)),
                ("target_fps", models.FloatField(default=6.0)),
                (
                    "rotation",
                    models.IntegerField(
                        choices=[(0, "0°"), (90, "90°"), (180, "180°"), (270, "270°")],
                        default=0,
                    ),
                ),
                ("enabled_analytics", models.JSONField(blank=True, default=list)),
                ("analytics_config", models.JSONField(blank=True, default=dict)),
                ("model_overrides", models.JSONField(blank=True, default=dict)),
                ("record_evidence", models.BooleanField(default=True)),
                ("evidence_seconds", models.PositiveIntegerField(default=10)),
                ("privacy_blur_faces", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="cameras/thumbnails/"
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("health", models.JSONField(blank=True, default=dict)),
                ("frames_processed", models.BigIntegerField(default=0)),
                ("events_generated", models.BigIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="accounts.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cameras",
                        to="cameras.site",
                    ),
                ),
            ],
            options={
                "ordering": ["site__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("restricted", "Restricted area"),
                            ("hazard", "Hazard zone"),
                            ("monitored", "Monitored area"),
                            ("counting", "Counting / occupancy area"),
                            ("shelf", "Stock / shelf area"),
                            ("exclusion", "Exclusion (ignore this area)"),
                        ],
                        default="restricted",
                        max_length=16,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="high",
                        max_length=10,
                    ),
                ),
                ("polygon", models.JSONField(default=list)),
                ("colour", models.CharField(default="#ef4444", max_length=7)),
                ("schedule", models.JSONField(blank=True, default=dict)),
                (
                    "max_occupancy",
                    models.PositiveIntegerField(default=0, help_text="0 = no limit"),
                ),
                (
                    "min_dwell_seconds",
                    models.PositiveIntegerField(
                        default=0, help_text="0 = alert on entry"
                    ),
                ),
                (
                    "allowed_roles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Employee roles permitted here",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zones",
                        to="cameras.camera",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["camera", "name"],
            },
        ),
        migrations.CreateModel(
            name="CameraSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("image", models.ImageField(upload_to="snapshots/%Y/%m/%d/")),
                (
                    "captured_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("width", models.PositiveIntegerField(default=0)),
                ("height", models.PositiveIntegerField(default=0)),
                ("reason", models.CharField(blank=True, max_length=60)),
                ("annotations", models.JSONField(blank=True, default=dict)),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="cameras.camera",
                    ),
                ),
            ],
            options={
                "ordering": ["-captured_at"],
                "indexes": [
                    models.Index(
                        fields=["camera", "-captured_at"],
                        name="cameras_cam_camera__87766d_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="site",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="uniq_site_name_per_org"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["organization", "is_active"],
                name="cameras_emp_organiz_07b179_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.UniqueConstraint(
                condition=models.Q(("employee_code", ""), _negated=True),
                fields=("organization", "employee_code"),
                name="uniq_employee_code_per_org",
            ),
        ),
        migrations.AddIndex(
            model_name="camera",
            index=models.Index(
                fields=["organization", "status"], name="cameras_cam_organiz_d620df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="camera",
            index=models.Index(
                fields=["site", "is_active"], name="cameras_cam_site_id_441269_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="camera",
            constraint=models.UniqueConstraint(
                fields=("site", "name"), name="uniq_camera_name_per_site"
            ),
        ),
        migrations.AddIndex(
            model_name="zone",
            index=models.Index(
                fields=["camera", "is_active"], name="cameras_zon_camera__b59fe8_idx"
            ),
        ),
    ]
