# Generated by Django 5.1.4 on 2026-09-10 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("cameras", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camera",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cameras",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sites",
                to="accounts.organization",
            ),
        ),
    ]
