# Generated by Django 5.1.4 on 2026-09-10 18:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("cameras", "0001_initial"),
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                (
                    "task",
                    models.CharField(
                        choices=[
                            ("classification", "Image classification"),
                            ("embedding", "Identity embedding"),
                            ("detection", "Object detection"),
                            ("density", "Crowd density"),
                            ("multilabel", "Multi-label classification"),
                        ],
                        default="classification",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("labelling", "Labelling"),
                            ("ready", "Ready to train"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("classes", models.JSONField(blank=True, default=list)),
                ("image_size", models.PositiveIntegerField(default=96)),
                ("channels", models.PositiveIntegerField(default=3)),
                ("validation_split", models.FloatField(default=0.2)),
                (
                    "augmentation",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="{'flip': true, 'brightness': 0.2, 'noise': 0.05, 'shift': 0.1}",
                    ),
                ),
                ("sample_count", models.PositiveIntegerField(default=0)),
                ("labelled_count", models.PositiveIntegerField(default=0)),
                ("class_distribution", models.JSONField(blank=True, default=dict)),
                (
                    "harvest_from_events",
                    models.BooleanField(
                        default=False,
                        help_text="Add frames from events operators marked as false positives.",
                    ),
                ),
                ("harvest_analytics", models.JSONField(blank=True, default=list)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="accounts.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DatasetSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="datasets/%Y/%m/"
                    ),
                ),
                ("features", models.JSONField(blank=True, default=list)),
                ("label", models.CharField(blank=True, db_index=True, max_length=120)),
                ("annotations", models.JSONField(blank=True, default=list)),
                (
                    "split",
                    models.CharField(
                        choices=[
                            ("train", "Train"),
                            ("validation", "Validation"),
                            ("test", "Test"),
                        ],
                        db_index=True,
                        default="train",
                        max_length=12,
                    ),
                ),
                ("labelled_at", models.DateTimeField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("notes", models.CharField(blank=True, max_length=300)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="training.dataset",
                    ),
                ),
                (
                    "labelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="labelled_samples",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_camera",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dataset_samples",
                        to="cameras.camera",
                    ),
                ),
                (
                    "source_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dataset_samples",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                (
                    "architecture",
                    models.CharField(
                        choices=[
                            ("campynet", "CampyNet — image classifier"),
                            ("campyface", "CampyFace — identity embedding"),
                            ("campydet", "CampyDet — object detector"),
                            ("campydense", "CampyDense — crowd density"),
                            ("campyseq", "CampySeq — temporal action"),
                        ],
                        default="campynet",
                        max_length=20,
                    ),
                ),
                (
                    "target_slot",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("campydet", "Person & object detector"),
                            ("campyface", "Face identity embedding"),
                            ("campynet_face", "Face / not-face verifier"),
                            ("campynet_fire", "Fire & smoke classifier"),
                            ("campynet_object", "Object classifier"),
                            ("campydense", "Crowd density estimator"),
                            ("campyseq_gesture", "Gesture & posture sequence model"),
                        ],
                        max_length=32,
                    ),
                ),
                ("epochs", models.PositiveIntegerField(default=25)),
                ("batch_size", models.PositiveIntegerField(default=32)),
                ("learning_rate", models.FloatField(default=0.001)),
                (
                    "optimizer",
                    models.CharField(
                        choices=[
                            ("adam", "Adam"),
                            ("adamw", "AdamW"),
                            ("sgd", "SGD with momentum"),
                        ],
                        default="adam",
                        max_length=12,
                    ),
                ),
                (
                    "loss_function",
                    models.CharField(default="cross_entropy", max_length=24),
                ),
                (
                    "schedule",
                    models.CharField(
                        choices=[
                            ("constant", "Constant"),
                            ("step", "Step decay"),
                            ("cosine", "Cosine annealing"),
                        ],
                        default="cosine",
                        max_length=12,
                    ),
                ),
                (
                    "width",
                    models.FloatField(
                        default=1.0, help_text="Channel multiplier — capacity vs speed"
                    ),
                ),
                ("depth", models.PositiveIntegerField(default=3)),
                ("dropout", models.FloatField(default=0.25)),
                (
                    "early_stopping_patience",
                    models.PositiveIntegerField(default=6, help_text="0 = disabled"),
                ),
                ("seed", models.IntegerField(default=1337)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=12,
                    ),
                ),
                ("progress", models.FloatField(default=0.0)),
                ("current_epoch", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(default=0.0)),
                ("error_message", models.TextField(blank=True)),
                ("cancel_requested", models.BooleanField(default=False)),
                ("history", models.JSONField(blank=True, default=list)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("log", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="training.dataset",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="accounts.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModelVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("version", models.CharField(default="1.0.0", max_length=32)),
                (
                    "slot",
                    models.CharField(
                        choices=[
                            ("campydet", "Person & object detector"),
                            ("campyface", "Face identity embedding"),
                            ("campynet_face", "Face / not-face verifier"),
                            ("campynet_fire", "Fire & smoke classifier"),
                            ("campynet_object", "Object classifier"),
                            ("campydense", "Crowd density estimator"),
                            ("campyseq_gesture", "Gesture & posture sequence model"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "architecture",
                    models.CharField(
                        choices=[
                            ("campynet", "CampyNet — image classifier"),
                            ("campyface", "CampyFace — identity embedding"),
                            ("campydet", "CampyDet — object detector"),
                            ("campydense", "CampyDense — crowd density"),
                            ("campyseq", "CampySeq — temporal action"),
                        ],
                        default="campynet",
                        max_length=20,
                    ),
                ),
                (
                    "task",
                    models.CharField(
                        choices=[
                            ("classification", "Image classification"),
                            ("embedding", "Identity embedding"),
                            ("detection", "Object detection"),
                            ("density", "Crowd density"),
                            ("multilabel", "Multi-label classification"),
                        ],
                        default="classification",
                        max_length=20,
                    ),
                ),
                ("weights_path", models.CharField(blank=True, max_length=500)),
                ("file_size_bytes", models.BigIntegerField(default=0)),
                ("parameter_count", models.BigIntegerField(default=0)),
                ("classes", models.JSONField(blank=True, default=list)),
                ("input_size", models.PositiveIntegerField(default=96)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("accuracy", models.FloatField(default=0.0)),
                ("precision", models.FloatField(default=0.0)),
                ("recall", models.FloatField(default=0.0)),
                ("f1_score", models.FloatField(default=0.0)),
                ("evaluation", models.JSONField(blank=True, default=dict)),
                ("inference_ms", models.FloatField(default=0.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ready", "Ready"),
                            ("deployed", "Deployed"),
                            ("archived", "Archived"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
                (
                    "is_base_model",
                    models.BooleanField(
                        default=False,
                        help_text="Provided by Campy AI to all workspaces",
                    ),
                ),
                ("deployed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versions",
                        to="training.dataset",
                    ),
                ),
                (
                    "deployed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deployed_models",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_versions",
                        to="accounts.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versions",
                        to="training.trainingjob",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="dataset",
            index=models.Index(
                fields=["organization", "status"], name="training_da_organiz_b2c2f1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dataset",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="uniq_dataset_name_per_org"
            ),
        ),
        migrations.AddIndex(
            model_name="datasetsample",
            index=models.Index(
                fields=["dataset", "label"], name="training_da_dataset_b40cda_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datasetsample",
            index=models.Index(
                fields=["dataset", "split"], name="training_da_dataset_43cbc2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainingjob",
            index=models.Index(
                fields=["organization", "status", "-created_at"],
                name="training_tr_organiz_0955d9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="modelversion",
            index=models.Index(
                fields=["organization", "slot", "status"],
                name="training_mo_organiz_765d12_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="modelversion",
            index=models.Index(
                fields=["slot", "is_base_model"], name="training_mo_slot_3e0397_idx"
            ),
        ),
    ]
