# Generated by Django 5.1.4 on 2026-09-10 18:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("cameras", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("safety", "Safety summary"),
                            ("activity", "Activity & attendance"),
                            ("incidents", "Incident log"),
                            ("crowd", "Crowd & occupancy"),
                            ("compliance", "Compliance / audit"),
                            ("custom", "Custom"),
                        ],
                        default="safety",
                        max_length=12,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("once", "One-off"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="once",
                        max_length=10,
                    ),
                ),
                (
                    "output_format",
                    models.CharField(
                        choices=[("html", "HTML"), ("csv", "CSV"), ("pdf", "PDF")],
                        default="html",
                        max_length=6,
                    ),
                ),
                ("analytics", models.JSONField(blank=True, default=list)),
                ("date_range_days", models.PositiveIntegerField(default=7)),
                ("filters", models.JSONField(blank=True, default=dict)),
                (
                    "recipients",
                    models.JSONField(
                        blank=True, default=list, help_text="Email addresses"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("run_count", models.PositiveIntegerField(default=0)),
                (
                    "cameras",
                    models.ManyToManyField(
                        blank=True, related_name="reports", to="cameras.camera"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="accounts.organization",
                    ),
                ),
                (
                    "sites",
                    models.ManyToManyField(
                        blank=True, related_name="reports", to="cameras.site"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=10,
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="reports/%Y/%m/"),
                ),
                ("error", models.CharField(blank=True, max_length=400)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_to", models.JSONField(blank=True, default=list)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="analytics.report",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("target", models.CharField(default="events", max_length=40)),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("is_shared", models.BooleanField(default=False)),
                ("is_default", models.BooleanField(default=False)),
                ("use_count", models.PositiveIntegerField(default=0)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="accounts.organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DailyMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True)),
                ("events_total", models.PositiveIntegerField(default=0)),
                ("events_critical", models.PositiveIntegerField(default=0)),
                ("events_high", models.PositiveIntegerField(default=0)),
                ("events_by_analytic", models.JSONField(blank=True, default=dict)),
                ("events_by_hour", models.JSONField(blank=True, default=list)),
                ("incidents_opened", models.PositiveIntegerField(default=0)),
                ("incidents_resolved", models.PositiveIntegerField(default=0)),
                ("false_positives", models.PositiveIntegerField(default=0)),
                ("median_response_seconds", models.FloatField(default=0.0)),
                ("people_peak", models.PositiveIntegerField(default=0)),
                ("people_average", models.FloatField(default=0.0)),
                ("unique_employees", models.PositiveIntegerField(default=0)),
                ("frames_processed", models.BigIntegerField(default=0)),
                ("camera_uptime_percent", models.FloatField(default=0.0)),
                (
                    "camera",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_metrics",
                        to="cameras.camera",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="accounts.organization",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_metrics",
                        to="cameras.site",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["organization", "-date"],
                        name="analytics_d_organiz_583fae_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "date", "site", "camera"),
                        name="uniq_daily_metric",
                    )
                ],
            },
        ),
    ]
