# Generated by Django 5.1.4 on 2026-09-10 18:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("colour", models.CharField(default="#4f46e5", max_length=7)),
                ("sort_order", models.PositiveIntegerField(default=100)),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("question", models.CharField(max_length=300)),
                ("answer", models.TextField()),
                ("category", models.CharField(blank=True, max_length=80)),
                ("sort_order", models.PositiveIntegerField(default=100)),
                ("is_published", models.BooleanField(default=True)),
                ("helpful_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["sort_order", "question"],
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("header", "Header"),
                            ("footer_product", "Footer — Product"),
                            ("footer_company", "Footer — Company"),
                            ("footer_legal", "Footer — Legal"),
                            ("dashboard", "Dashboard"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
            ],
            options={
                "ordering": ["location"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("site_name", models.CharField(default="Campy AI", max_length=120)),
                (
                    "tagline",
                    models.CharField(
                        default="Turn ordinary CCTV into workplace intelligence",
                        max_length=220,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="cms/brand/"),
                ),
                (
                    "logo_dark",
                    models.ImageField(blank=True, null=True, upload_to="cms/brand/"),
                ),
                (
                    "favicon",
                    models.ImageField(blank=True, null=True, upload_to="cms/brand/"),
                ),
                (
                    "contact_email",
                    models.EmailField(default="hello@campy.ai", max_length=254),
                ),
                (
                    "support_email",
                    models.EmailField(default="support@campy.ai", max_length=254),
                ),
                ("sales_phone", models.CharField(blank=True, max_length=32)),
                ("address", models.TextField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("default_seo_title", models.CharField(blank=True, max_length=70)),
                (
                    "default_seo_description",
                    models.CharField(blank=True, max_length=180),
                ),
                ("google_analytics_id", models.CharField(blank=True, max_length=40)),
                ("custom_head_html", models.TextField(blank=True)),
                ("custom_footer_html", models.TextField(blank=True)),
                ("primary_colour", models.CharField(default="#4f46e5", max_length=7)),
                ("accent_colour", models.CharField(default="#06b6d4", max_length=7)),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("maintenance_message", models.TextField(blank=True)),
                ("signups_enabled", models.BooleanField(default=True)),
                ("announcement", models.CharField(blank=True, max_length=300)),
                ("announcement_url", models.CharField(blank=True, max_length=300)),
            ],
            options={
                "verbose_name": "Site settings",
                "verbose_name_plural": "Site settings",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                ("name", models.CharField(max_length=80)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("quote", models.TextField()),
                ("author_name", models.CharField(max_length=140)),
                ("author_title", models.CharField(blank=True, max_length=160)),
                ("company", models.CharField(blank=True, max_length=160)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="cms/testimonials/"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="cms/logos/"),
                ),
                ("rating", models.PositiveSmallIntegerField(default=5)),
                ("industry", models.CharField(blank=True, max_length=80)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=100)),
            ],
            options={
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("document", "Document"),
                            ("video", "Video"),
                        ],
                        default="image",
                        max_length=10,
                    ),
                ),
                ("file", models.FileField(upload_to="cms/library/%Y/%m/")),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Required for accessibility",
                        max_length=250,
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=300)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("width", models.PositiveIntegerField(default=0)),
                ("height", models.PositiveIntegerField(default=0)),
                ("file_size", models.BigIntegerField(default=0)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "In review"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, help_text="Best under 60 characters", max_length=70
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True,
                        help_text="Best under 160 characters",
                        max_length=180,
                    ),
                ),
                ("seo_keywords", models.CharField(blank=True, max_length=250)),
                (
                    "og_image",
                    models.ImageField(blank=True, null=True, upload_to="cms/og/"),
                ),
                ("canonical_url", models.URLField(blank=True)),
                ("no_index", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "template",
                    models.CharField(
                        choices=[
                            ("default", "Standard page"),
                            ("landing", "Landing page"),
                            ("full_width", "Full width"),
                            ("legal", "Legal / policy"),
                            ("contact", "Contact"),
                        ],
                        default="default",
                        max_length=16,
                    ),
                ),
                ("excerpt", models.TextField(blank=True)),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="Markdown-ish body used when no blocks are defined",
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="cms/pages/"),
                ),
                ("show_in_navigation", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=100)),
                ("is_homepage", models.BooleanField(default=False)),
                ("view_count", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="cms.page",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_published",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("label", models.CharField(max_length=80)),
                ("url", models.CharField(blank=True, max_length=300)),
                (
                    "named_url",
                    models.CharField(
                        blank=True,
                        help_text="Django URL name, e.g. cms:pricing",
                        max_length=120,
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=40)),
                ("sort_order", models.PositiveIntegerField(default=100)),
                ("is_visible", models.BooleanField(default=True)),
                ("open_in_new_tab", models.BooleanField(default=False)),
                (
                    "highlight",
                    models.BooleanField(default=False, help_text="Render as a button"),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cms.menu",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="cms.menuitem",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="menu_items",
                        to="cms.page",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "label"],
            },
        ),
        migrations.CreateModel(
            name="ContentBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("hero", "Hero banner"),
                            ("rich_text", "Rich text"),
                            ("features", "Feature grid"),
                            ("stats", "Statistics band"),
                            ("cta", "Call to action"),
                            ("testimonials", "Testimonials"),
                            ("pricing", "Pricing table"),
                            ("faq", "FAQ accordion"),
                            ("logos", "Logo strip"),
                            ("gallery", "Image gallery"),
                            ("steps", "Process steps"),
                            ("video", "Video embed"),
                            ("contact_form", "Contact form"),
                            ("html", "Raw HTML"),
                        ],
                        default="rich_text",
                        max_length=16,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=100)),
                ("is_visible", models.BooleanField(default=True)),
                ("heading", models.CharField(blank=True, max_length=220)),
                ("subheading", models.CharField(blank=True, max_length=320)),
                ("body", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="cms/blocks/"),
                ),
                ("primary_label", models.CharField(blank=True, max_length=60)),
                ("primary_url", models.CharField(blank=True, max_length=300)),
                ("secondary_label", models.CharField(blank=True, max_length=60)),
                ("secondary_url", models.CharField(blank=True, max_length=300)),
                ("items", models.JSONField(blank=True, default=list)),
                ("options", models.JSONField(blank=True, default=dict)),
                (
                    "background",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("accent", "Accent"),
                            ("muted", "Muted"),
                        ],
                        default="light",
                        max_length=12,
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="cms.page",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "In review"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, help_text="Best under 60 characters", max_length=70
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True,
                        help_text="Best under 160 characters",
                        max_length=180,
                    ),
                ),
                ("seo_keywords", models.CharField(blank=True, max_length=250)),
                (
                    "og_image",
                    models.ImageField(blank=True, null=True, upload_to="cms/og/"),
                ),
                ("canonical_url", models.URLField(blank=True)),
                ("no_index", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=240)),
                ("slug", models.SlugField(blank=True, max_length=240, unique=True)),
                ("excerpt", models.TextField(blank=True)),
                ("body", models.TextField(blank=True)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="cms/posts/"),
                ),
                (
                    "author_name",
                    models.CharField(
                        blank=True,
                        help_text="Overrides the linked author",
                        max_length=140,
                    ),
                ),
                ("reading_minutes", models.PositiveIntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                ("view_count", models.PositiveIntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="cms.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_published",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="posts", to="cms.tag"
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("company", models.CharField(blank=True, max_length=180)),
                ("job_title", models.CharField(blank=True, max_length=120)),
                ("country", models.CharField(blank=True, max_length=80)),
                ("industry", models.CharField(blank=True, max_length=80)),
                ("camera_count", models.CharField(blank=True, max_length=40)),
                ("message", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("contact", "Contact form"),
                            ("demo", "Demo request"),
                            ("pricing", "Pricing enquiry"),
                            ("newsletter", "Newsletter"),
                        ],
                        default="contact",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("qualified", "Qualified"),
                            ("converted", "Converted"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=12,
                    ),
                ),
                ("internal_notes", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("referrer", models.CharField(blank=True, max_length=300)),
                ("utm", models.JSONField(blank=True, default=dict)),
                ("contacted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "interested_package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="billing.package",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="cms_lead_status_a5db10_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="page",
            index=models.Index(
                fields=["status", "slug"], name="cms_page_status_d77f38_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["status", "-published_at"], name="cms_post_status_1de8ed_idx"
            ),
        ),
    ]
